# Clean Strava file

This notebook is used to clean the Strava file. It rewrites the file **strava_ips.xlsx**. It performs the following operations:
* Delete the rows with more than 50% of missing.
* Clean dates to read with Looker Studio. Google sheets does not recognize the date format.
* Clean white spaces in the columns.
* Convert the numeric columns so that they are recognized as numbers in Looker Studio.

The data in the file strava_ips.xlsx should be copied to the Google sheet **Strava_IPS**. 
* Open your Google drive in your working directory. Here you will get your Google sheet. 
* Copy the file strava_ips.xlsx in the above directory.
* Open the Excel file in the drive. Copy and paste the data to the Google sheet Strava_IPS.

## Read file

In [1]:
import pandas as pd

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# Open file activities.csv
df0 = pd.read_csv('../data/activities.csv')
df0.tail(3)

,Id. de actividad,Fecha de la actividad,Nombre de la actividad,Tipo de actividad,Descripción de la actividad,Tiempo transcurrido,Distancia,Ritmo cardíaco máx.,Esfuerzo relativo,Viaje al trabajo,Nota privada de actividad,Equipamiento de la actividad,Nombre de archivo,Peso del atleta,Peso de la bicicleta,Tiempo transcurrido.1,Tiempo en movimiento,Distancia.1,Velocidad máxima,Velocidad promedio,Desnivel positivo,Desnivel negativo,Desnivel bajo,Desnivel alto,Grado máximo,Pendiente promedio,Grado positivo promedio,Grado negativo promedio,Cadencia máx.,Cadencia promedio,Ritmo cardíaco máx..1,Ritmo cardíaco promedio,Máx. de vatios,Vatios promedio,Calorías,Temperatura máx.,Temperatura promedio,Esfuerzo relativo.1,Esfuerzo total,Cantidad de carreras,Tiempo de ascenso,Tiempo de descenso,Otro tiempo,Esfuerzo Percibido,Tipo,Hora de inicio,Potencia promedio ponderada,Conteo de potencia,Usar Esfuerzo Percibido,Esfuerzo relativo percibido,Viaje al trabajo.1,Peso total levantado,De carga,Distancia ajustada en pendientes,Tiempo de observación del clima,Condición climática,Temperatura,Sensación térmica,Punto de rocío,Humedad,Presión atmosférica,Velocidad del viento,Ráfaga de viento,Dirección del viento,Intensidad de la precipitación,Hora de salida del sol,Hora de puesta del sol,Fase lunar,Bicicleta,Equipamiento,Probabilidad de precipitación,Tipo de precipitación,Nubosidad,Visibilidad,Índice UV,Estado del ozono,Recuento de saltos,Complejidad total,Fluidez promedio,Marcado,Velocidad promedio durante el tiempo transcurrido,Distancia sobre tierra,Distancia recién recorrida,Distancia recién recorrida en caminos sin asfaltar,Número de actividades,Pasos en total,Emisión de carbono evitada,Largo de la piscina,Carga de entrenamiento,Intensidad,Ritmo ajustado en pendientes promedio,Tiempo del cronómetro,Ciclos en total,Multimedia
2639,15220738336,26 jul. 2014 12:41:26,Mazatlán - Potrerillos,Vuelta ciclista,Tour Ruta Chichimeca,37254,131.10,NaN,NaN,False,NaN,Trek X-Caliber 9,activities/16254394819.gpx.gz,NaN,14.5,37254.0,29261.0,131105.859375,15.921565,4.480567,1617.736084,493.80426,1.2,1522.900024,24.581144,1.158453,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.030838,3198.354248,NaN,37.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5230367.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.519243,931.599976,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2640,15227330540,24 jul. 2025 17:39:34,Ley del Valle,Caminata,Culiacán,3282,3.59,101.0,5.0,False,NaN,Adidas Terrex Eastrail,activities/16261402744.fit.gz,NaN,NaN,3282.0,2932.0,3596.199951,2.174000,1.097000,24.024540,167.00000,28.1,43.500000,20.270269,0.000000,NaN,NaN,80.0,35.0,101.0,79.0,NaN,NaN,244.000000,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11968176.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.095734,0.000000,NaN,NaN,NaN,4130.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2641,15227332434,25 jul. 2025 00:06:29,La Platanera,Vuelta ciclista,NaN,8409,51.85,149.0,56.0,False,NaN,Trek X-Caliber 9,activities/16261404830.fit.gz,NaN,14.5,8409.0,8242.0,51856.101562,12.699000,6.168000,145.078339,200.00000,18.1,47.700001,7.416268,0.000771,NaN,NaN,NaN,NaN,149.0,121.0,NaN,83.107635,1044.000000,NaN,NaN,56.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5230367.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.166738,5363.000000,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Delete half empty columns

In [2]:
# Count missing values in each column. Sort from highest to lowest.
missing_values = df0.isnull().sum().sort_values(ascending=False)
missing_values

Grado negativo promedio                               2642
Grado positivo promedio                               2642
Hora de puesta del sol                                2642
Fase lunar                                            2642
Tipo de precipitación                                 2642
Probabilidad de precipitación                         2642
Índice UV                                             2642
Estado del ozono                                      2642
Tiempo de observación del clima                       2642
Condición climática                                   2642
Velocidad del viento                                  2642
Presión atmosférica                                   2642
Humedad                                               2642
Punto de rocío                                        2642
Potencia promedio ponderada                           2642
Conteo de potencia                                    2642
Esfuerzo relativo percibido                           2642
Peso total levantado                                  2642
Sensación térmica                                     2642
Temperatura                                           2642
Hora de inicio                                        2642
Tipo                                                  2642
Esfuerzo total                                        2642
Cantidad de carreras                                  2642
Tiempo de ascenso                                     2642
Tiempo de descenso                                    2642
Otro tiempo                                           2642
Esfuerzo Percibido                                    2642
Temperatura máx.                                      2642
Máx. de vatios                                        2642
Ciclos en total                                       2642
Intensidad                                            2642
Distancia recién recorrida en caminos sin asfaltar    2642
Distancia recién recorrida                            2642
Tiempo del cronómetro                                 2642
Largo de la piscina                                   2642
Carga de entrenamiento                                2642
Fluidez promedio                                      2642
Recuento de saltos                                    2642
Complejidad total                                     2642
Nubosidad                                             2642
Visibilidad                                           2642
Número de actividades                                 2642
Intensidad de la precipitación                        2642
Dirección del viento                                  2642
Ráfaga de viento                                      2642
Hora de salida del sol                                2642
Nota privada de actividad                             2641
Ritmo ajustado en pendientes promedio                 2616
Multimedia                                            2509
Distancia ajustada en pendientes                      2497
Pasos en total                                        2328
Cadencia máx.                                         2324
Cadencia promedio                                     2324
Emisión de carbono evitada                            2165
Temperatura promedio                                  2134
Descripción de la actividad                           2132
Equipamiento                                          2026
Peso del atleta                                       2018
Ritmo cardíaco máx..1                                 1449
Ritmo cardíaco promedio                                816
Marcado                                                799
Ritmo cardíaco máx.                                    780
Esfuerzo relativo                                      780
Esfuerzo relativo.1                                    780
Velocidad promedio durante el tiempo transcurrido      766
Vatios promedio                                        615
Peso de la bicicleta                                   614
De carga                                               614
Bicicleta                                              610
Usar Esfuerzo Percibido                                598
Velocidad promedio                                     598
Distancia sobre tierra                                 436
Desnivel negativo                                      121
Viaje al trabajo.1                                      58
Desnivel alto                                           42
Desnivel bajo                                           42
Nombre de archivo                                       37
Desnivel positivo                                       37
Grado máximo                                            37
Velocidad máxima                                        37
Calorías                                                22
Tiempo transcurrido.1                                   21
Equipamiento de la actividad                             3
Pendiente promedio                                       0
Tiempo en movimiento                                     0
Nombre de la actividad                                   0
Tiempo transcurrido                                      0
Distancia.1                                              0
Fecha de la actividad                                    0
Id. de actividad                                         0
Tipo de actividad                                        0
Viaje al trabajo                                         0
Distancia                                                0
dtype: int64

In [3]:
# Drop columns with 50% missing values, but keep 'Descripción de la actividad'
cols_to_keep = ['Descripción de la actividad']
cols_above_thresh = df0.dropna(thresh=df0.shape[0]*0.5, axis=1).columns.tolist()
cols_final = [col for col in df0.columns if col in cols_above_thresh and col not in cols_to_keep]
cols_final += cols_to_keep  # Ensure 'Descripción de la actividad' is at the end
df1 = df0[cols_final]

# Count missing values in each column. Sort from highest to lowest.
missing_values = df1.isnull().sum().sort_values(ascending=False)
missing_values

Descripción de la actividad                          2132
Ritmo cardíaco promedio                               816
Marcado                                               799
Esfuerzo relativo.1                                   780
Esfuerzo relativo                                     780
Ritmo cardíaco máx.                                   780
Velocidad promedio durante el tiempo transcurrido     766
Vatios promedio                                       615
Peso de la bicicleta                                  614
De carga                                              614
Bicicleta                                             610
Usar Esfuerzo Percibido                               598
Velocidad promedio                                    598
Distancia sobre tierra                                436
Desnivel negativo                                     121
Viaje al trabajo.1                                     58
Desnivel alto                                          42
Desnivel bajo                                          42
Velocidad máxima                                       37
Desnivel positivo                                      37
Grado máximo                                           37
Nombre de archivo                                      37
Calorías                                               22
Tiempo transcurrido.1                                  21
Equipamiento de la actividad                            3
Id. de actividad                                        0
Fecha de la actividad                                   0
Nombre de la actividad                                  0
Distancia.1                                             0
Tiempo en movimiento                                    0
Viaje al trabajo                                        0
Distancia                                               0
Tiempo transcurrido                                     0
Tipo de actividad                                       0
Pendiente promedio                                      0
dtype: int64

In [4]:
df1.tail()

,Id. de actividad,Fecha de la actividad,Nombre de la actividad,Tipo de actividad,Tiempo transcurrido,Distancia,Ritmo cardíaco máx.,Esfuerzo relativo,Viaje al trabajo,Equipamiento de la actividad,Nombre de archivo,Peso de la bicicleta,Tiempo transcurrido.1,Tiempo en movimiento,Distancia.1,Velocidad máxima,Velocidad promedio,Desnivel positivo,Desnivel negativo,Desnivel bajo,Desnivel alto,Grado máximo,Pendiente promedio,Ritmo cardíaco promedio,Vatios promedio,Calorías,Esfuerzo relativo.1,Usar Esfuerzo Percibido,Viaje al trabajo.1,De carga,Bicicleta,Marcado,Velocidad promedio durante el tiempo transcurrido,Distancia sobre tierra,Descripción de la actividad
2637,15220567000,14 sep. 2013 10:20:46,Durango - Mazatlán,Vuelta ciclista,52883,256.22,NaN,NaN,False,Trek X-Caliber 9,activities/16254211104.gpx.gz,14.5,52883.0,37419.0,256221.093750,23.754728,6.847353,4101.606934,5634.478516,1.5,2741.699951,49.995838,-0.743616,NaN,120.193291,5014.714355,NaN,NaN,0.0,1.0,5230367.0,0.0,4.845056,15.400000,Tour Ruta Chichimeca
2638,15220633781,26 jul. 2017 15:46:38,Mazatlán - Potrerillos,Vuelta ciclista,33601,103.21,142.0,97.0,False,Trek X-Caliber 9,activities/16254282832.gpx.gz,14.5,33601.0,24048.0,103217.960938,17.015110,4.292164,2071.595703,554.852356,1.2,1520.099976,24.497150,1.470093,112.553719,110.959236,2975.201416,97.0,NaN,0.0,1.0,5230367.0,NaN,3.071872,808.099976,Tour Ruta Chichimeca
2639,15220738336,26 jul. 2014 12:41:26,Mazatlán - Potrerillos,Vuelta ciclista,37254,131.10,NaN,NaN,False,Trek X-Caliber 9,activities/16254394819.gpx.gz,14.5,37254.0,29261.0,131105.859375,15.921565,4.480567,1617.736084,493.804260,1.2,1522.900024,24.581144,1.158453,NaN,98.030838,3198.354248,NaN,NaN,0.0,1.0,5230367.0,NaN,3.519243,931.599976,Tour Ruta Chichimeca
2640,15227330540,24 jul. 2025 17:39:34,Ley del Valle,Caminata,3282,3.59,101.0,5.0,False,Adidas Terrex Eastrail,activities/16261402744.fit.gz,NaN,3282.0,2932.0,3596.199951,2.174000,1.097000,24.024540,167.000000,28.1,43.500000,20.270269,0.000000,79.000000,NaN,244.000000,5.0,NaN,0.0,1.0,NaN,NaN,1.095734,0.000000,Culiacán
2641,15227332434,25 jul. 2025 00:06:29,La Platanera,Vuelta ciclista,8409,51.85,149.0,56.0,False,Trek X-Caliber 9,activities/16261404830.fit.gz,14.5,8409.0,8242.0,51856.101562,12.699000,6.168000,145.078339,200.000000,18.1,47.700001,7.416268,0.000771,121.000000,83.107635,1044.000000,56.0,NaN,0.0,1.0,5230367.0,NaN,6.166738,5363.000000,NaN

## Parse date

In [5]:
# Split the column 'Fecha de la actividad' into 4 columns
dfdate = df0['Fecha de la actividad'].str.split(expand=True).rename(columns={0: 'Day', 1: 'Month', 2: 'Year', 3: 'Time'})
# Delete '.' from 'Month' column
dfdate['Month'] = dfdate['Month'].str.replace('.', '')
dfdate['Mont_Num'] = dfdate['Month'].str.replace('ene', '01').str.replace('feb', '02').str.replace('mar', '03').str.replace('abr', '04').str.replace('may', '05').str.replace('jun', '06').str.replace('jul', '07').str.replace('ago', '08').str.replace('sep', '09').str.replace('oct', '10').str.replace('nov', '11').str.replace('dic', '12')
# Convert numeric values to datetime
dfdate['Date'] = pd.to_datetime(dfdate['Year'] + '-' + dfdate['Mont_Num'] + '-' + dfdate['Day'])

# Define an empty dataframe
df1.loc[:,'Fecha de la actividad'] = dfdate['Date']
df1.tail()

,Id. de actividad,Fecha de la actividad,Nombre de la actividad,Tipo de actividad,Tiempo transcurrido,Distancia,Ritmo cardíaco máx.,Esfuerzo relativo,Viaje al trabajo,Equipamiento de la actividad,Nombre de archivo,Peso de la bicicleta,Tiempo transcurrido.1,Tiempo en movimiento,Distancia.1,Velocidad máxima,Velocidad promedio,Desnivel positivo,Desnivel negativo,Desnivel bajo,Desnivel alto,Grado máximo,Pendiente promedio,Ritmo cardíaco promedio,Vatios promedio,Calorías,Esfuerzo relativo.1,Usar Esfuerzo Percibido,Viaje al trabajo.1,De carga,Bicicleta,Marcado,Velocidad promedio durante el tiempo transcurrido,Distancia sobre tierra,Descripción de la actividad
2637,15220567000,2013-09-14 00:00:00,Durango - Mazatlán,Vuelta ciclista,52883,256.22,NaN,NaN,False,Trek X-Caliber 9,activities/16254211104.gpx.gz,14.5,52883.0,37419.0,256221.093750,23.754728,6.847353,4101.606934,5634.478516,1.5,2741.699951,49.995838,-0.743616,NaN,120.193291,5014.714355,NaN,NaN,0.0,1.0,5230367.0,0.0,4.845056,15.400000,Tour Ruta Chichimeca
2638,15220633781,2017-07-26 00:00:00,Mazatlán - Potrerillos,Vuelta ciclista,33601,103.21,142.0,97.0,False,Trek X-Caliber 9,activities/16254282832.gpx.gz,14.5,33601.0,24048.0,103217.960938,17.015110,4.292164,2071.595703,554.852356,1.2,1520.099976,24.497150,1.470093,112.553719,110.959236,2975.201416,97.0,NaN,0.0,1.0,5230367.0,NaN,3.071872,808.099976,Tour Ruta Chichimeca
2639,15220738336,2014-07-26 00:00:00,Mazatlán - Potrerillos,Vuelta ciclista,37254,131.10,NaN,NaN,False,Trek X-Caliber 9,activities/16254394819.gpx.gz,14.5,37254.0,29261.0,131105.859375,15.921565,4.480567,1617.736084,493.804260,1.2,1522.900024,24.581144,1.158453,NaN,98.030838,3198.354248,NaN,NaN,0.0,1.0,5230367.0,NaN,3.519243,931.599976,Tour Ruta Chichimeca
2640,15227330540,2025-07-24 00:00:00,Ley del Valle,Caminata,3282,3.59,101.0,5.0,False,Adidas Terrex Eastrail,activities/16261402744.fit.gz,NaN,3282.0,2932.0,3596.199951,2.174000,1.097000,24.024540,167.000000,28.1,43.500000,20.270269,0.000000,79.000000,NaN,244.000000,5.0,NaN,0.0,1.0,NaN,NaN,1.095734,0.000000,Culiacán
2641,15227332434,2025-07-25 00:00:00,La Platanera,Vuelta ciclista,8409,51.85,149.0,56.0,False,Trek X-Caliber 9,activities/16261404830.fit.gz,14.5,8409.0,8242.0,51856.101562,12.699000,6.168000,145.078339,200.000000,18.1,47.700001,7.416268,0.000771,121.000000,83.107635,1044.000000,56.0,NaN,0.0,1.0,5230367.0,NaN,6.166738,5363.000000,NaN

# Clean activity name

To clean the activity name, we perform the following operations:
* Replace the tag 'Vuelta ciclista' por 'Ciclismo', and filter  only cycling activities.
* Eliminate extra blank spaces.
* Replace 'Ciudad de México' by 'CDMX', in case there are both tags.

In [6]:
# Chage 'Vuelta ciclista' in column 'Tipo de actividad' to 'Ciclismo'
df1.loc[:,'Tipo de actividad'] = df0['Tipo de actividad'].replace('Vuelta ciclista', 'Ciclismo')

In [7]:
# Copy Id activity column to a new dataframe
dfact = df1.iloc[:, 0:1].copy()
dfact['Tipo de actividad'] = df1['Tipo de actividad']

# Eliminate extra blank spaces at the ends in 'Nombre de la actividad' column
dfact['Activity'] = df0['Nombre de la actividad'].str.strip()
# Clean 'Activity' from special characters. Use only lower letters and numbers.
#dfact['Activity'] = dfact['Activity'].str.replace(' ','_').str.replace('[^a-zA-Z0-9]', '').str.lower()
# Eliminate accentuated characters.
#dfact['Activity'] = dfact['Activity'].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')

In [8]:
# Replace 'Ciudad de México' with 'CDMX'
dfact['Activity'] = dfact['Activity'].str.replace('Ciudad de México', 'CDMX')
dfact['Activity'].value_counts()

Activity
Tec de Monterrey                        1083
Culiacán                                 300
Las Palmas 2                              75
Guadalupe                                 68
CDMX                                      54
Zacatecas                                 48
Navolato                                  38
Arroyo de la Plata                        31
Aguaruto                                  26
Ley del Valle                             20
San Pedro                                 16
La Platanera                              14
El Limón de los Ramos                     14
Aeropuerto                                13
Ley Palmito                               13
Ojocaliente                               12
Tolosa                                    12
Tacoaleche                                11
Central de autobuses                      11
El Batallón                               11
Solar Las Palmas 2                        11
Culiacán Centro                           11
San Jerónimo                              10
Vetagrande                                10
Trancoso                                  10
Costa Rica                                 9
La Zacatecana                              9
Infonavit Las Flores                       9
Altata                                     9
El Tamarindo                               8
Plaza Humaya                               8
Querétaro                                  8
Sauceda de la Borda                        7
Industrial El Palmito                      7
Caseta Salida Norte                        7
Imala                                      7
La Paz                                     7
Guadalupe Centro                           7
Culiacancito                               6
Palmira                                    6
San Rafael                                 6
Colonia Anáhuac                            6
Entronque La Curva                         6
Iguala                                     5
Plaza Azahares                             5
Plaza Ceiba                                5
Pemex                                      5
Villa Juárez                               5
Guadalupe - Aguascalientes                 5
Canal del Olmo                             4
Home Depot                                 4
Cerro de la Virgen                         4
Mojolo                                     4
El Pinole                                  4
Malecón de Mazatlán                        4
Chihuahua                                  4
Mazatlán                                   4
Cieneguitas                                4
Malpaso                                    4
La Palmita y Anexos                        4
La Sinaloa                                 4
Tepechitlán                                4
Parque Lineal Bugambilias                  4
La Curva                                   3
Fresnillo                                  3
Río Culiacán                               3
Morelos                                    3
Estadio Tomateros                          3
Plateros                                   3
Jerez                                      3
JAPAC                                      3
Zacatecas Centro                           3
La Peñita de Jaltemba                      3
Villanueva                                 3
Hospital La Raza                           3
El Alhuate                                 3
Plaza Fiesta                               3
La Guamuchilera                            3
Ciclobike                                  3
Los Becos                                  3
La Noria                                   3
Santa Mónica                               3
Topolobampo                                3
Infonavit Barrancos                        3
Feria Ganadera                             3
Durango                                    3
Bariometo                                  3
Naucalpan                                  3
Knoxville Downtown                         3
Calera                                     3
Nuevo Mundo                                3
Polanco                                    3
Cabo San Lucas                             3
Piedra Gorda                               3
Tepetate                                   3
Plaza Galerías                             2
Ejido Convención de Aguascalientes         2
Los Llamas                                 2
Boulevard Las Torres                       2
Flor de México                             2
Delia Barraza                              2
Cieneguillas                               2
Pozo de Gamboa                             2
Jesús María                                2
Taller Zavala                              2
Culiancito                                 2
Los Charritos                              2
Lomas del Boulevard                        2
El Palmito - Mazatlán                      2
Surutato                                   2
Campo Balbuena                             2
La Labor                                   2
San Isidro Bocanegra                       2
La Campana                                 2
Monterrey                                  2
Cola de Gato                               2
Infovanit Las Flores                       2
Santa Rocío                                2
El Quemadito                               2
La Cuesta                                  2
Los Linces                                 2
San Antonio del Ciprés                     2
Valdez Montoya                             2
Los Agaves                                 2
Rancho Los Migueles                        2
Bugambilias                                2
Fracc. Viñedos, Querétaro                  2
Yebavito                                   2
Nuevo Altata                               2
Bachigualato                               2
Smoky Mountains                            2
Bearden                                    2
Coyoacán                                   2
Potrerillos - El Salto                     2
Los Cascabeles                             2
Lo de Bartolo                              2
El Pozo                                    2
San Luis Potosí                            2
Xoconostle                                 2
La Bufa                                    2
Durango - Suchil                           2
Tepuche                                    2
Morningside Park                           2
Sequoyah Greenway                          2
Best Buy                                   2
Tickle Building                            2
Volunter Hall                              2
El Faro                                    2
Caseta Cuauhtémoc-Osiris                   2
Guadalupe - Colotlán                       2
Ojo de Agua del Progreso                   2
Mercado Guadalupe                          2
Mazatlán - Potrerillos                     2
Caimanero                                  2
La Condesa                                 1
Metro Normal                               1
La Lomita                                  1
Navolato a El Batallón                     1
Aurrerá Sanalona                           1
San Blas                                   1
Cascadas                                   1
Lomas de Chapultepec                       1
Alrededor Torre Pemex                      1
El árbol de la noche victoriosa            1
Presa Bicentenario                         1
Enrique Estrada                            1
Ojuelos - Dolores Hidalgo                  1
Dolores Hidalgo - Querétaro                1
Querétaro - San Juan del Río               1
Ley Plaza Fiesta                           1
Metro Revolución                           1
Viñedos                                    1
Desviación Chilitas                        1
INIFAP                                     1
Deportiva Norte                            1
El Carmen                                  1
Estación Catorce - Real del Catorce        1
Chavarría - Durango                        1
Guadalupe - Ojuelos                        1
Durango - Mazatlán                         1
Gasolinera                                 1
La Palmita                                 1
Mompaní                                    1
Aguascalientes - Lagos de Moreno           1
Laguna Seca                                1
Cofradía de Navolato                       1
Maratón CDMX                               1
Lakeshore Park                             1
Blount Knox Greenway                       1
Kelton Homes                               1
Knox County Health Department              1
TVB Store                                  1
Krutch Park                                1
Bearden Greenway                           1
Copper Cellar                              1
The Shire                                  1
Estadio Banorte                            1
Cerca Caseta                               1
Aguascalientes - León                      1
León - Celaya                              1
Celaya - Querétaro                         1
Guacamayas                                 1
Luis Moya                                  1
K98 - La Paz                               1
El Salto - Durango                         1
Pista Mina Bernabe                         1
Sataya                                     1
Mexiquillo                                 1
Díaz Ordaz                                 1
Xalitla                                    1
Chilitas                                   1
El Fuerte                                  1
Villanueva - Tlaltenango                   1
La Capilla                                 1
Esteban San Castorena                      1
San Pedro Piedra Gorda                     1
León                                       1
Mazatlán - Chavarría                       1
Iguala Centro                              1
Joyas del Atico                            1
Los Llanos                                 1
El Vergel                                  1
El Carrizal 2                              1
Planta SuKarne                             1
El Tambor                                  1
Dautillos                                  1
Knoxville Greenways                        1
Knox Plaza                                 1
Cherokee Farm                              1
Guadalupe - Pinos                          1
Moctezuma - San Antonio de Coronados       1
San Antonio de Coronados - Matehuala       1
Constituyentes                             1
Toreo                                      1
Felipe Ángeles                             1
El Palmito                                 1
Santa Lucía                                1
Mazatlán - El Palmito                      1
Las Higueras                               1
Cascada escondida                          1
San Pedro Garza García                     1
Agua Caliente de los Monzón                1
La Reforma                                 1
Badiraguato                                1
San Antonio de los Negros                  1
Coatzacoalcos - La Venta                   1
Veracruz - Buenavista                      1
Veracruz                                   1
La Joya                                    1
Sain Alto - Vicente Guerrero               1
Galería Zacatecas                          1
Chepinque - El Obraje                      1
El Obraje - San Luis Potosí                1
El Huejote                                 1
Valparaíso                                 1
Caseta Cuauhémoc-Osiris                    1
Guadalupe - Sain Alto                      1
Pánfilo Natera                             1
Susticacán                                 1
Duarte                                     1
Las Chilitas                               1
Joaquín Amaro                              1
Zacacoyuca                                 1
Juan M. Zambada                            1
Portezuelo                                 1
Las Brisas                                 1
Noria de Gringas                           1
Carrera Atlética Regency Club 21K          1
Guadalupe - Momax                          1
Real del Catorce                           1
Moctezuma - Estación Wadley                1
Noria de los Gringos Tacoaleche            1
Becos                                      1
Residencial Casa Blanca                    1
Concordia - El Palmito                     1
El Palmito - El Salto                      1
El Salto - Concordia                       1
Avenida Clouthier                          1
La Cortada                                 1
Antonio R. Vela                            1
Cruce Cd. Cuauhtemoc - Genaro Codina       1
Zacatecas - San Luis Potosí                1
La Quemada                                 1
Huitzuco                                   1
Tlaltenango                                1
Bernal                                     1
Palmillas                                  1
Santa Rosa Jauregui                        1
Guadalupe - Chepinque                      1
Sanalona                                   1
Avenida México                             1
Carrera de la Plata 21K                    1
Zona Conurbada                             1
Noria de los Gringos                       1
Plaza Carso                                1
Hipódromo                                  1
Tlatelolco                                 1
Parque Arroyo de la Plata                  1
Penitenciaria                              1
Durango - La Ciudad                        1
La Bebelama de San Pedro                   1
Los Ayales                                 1
El Guayabo                                 1
Lomas del Convento                         1
El Sauz                                    1
Cascadas San Antonio                       1
Tachinolpa                                 1
Cosalá                                     1
Las Puentes                                1
Culiacán centro                            1
Paralelo 38                                1
Entronque Campo Victoria                   1
Las Aguamitas                              1
Hotel Riu                                  1
Soriana Zapata                             1
Restaurante Narcisa                        1
Sombrerete                                 1
Parque Temático Militar                    1
Cerrajería Forza                           1
Panadería Flor de México                   1
Parque de la Revolución                    1
Eldorado                                   1
El Dique                                   1
El Carrizal                                1
Juan Escutia                               1
Los Mochis                                 1
Guasave                                    1
Capilla Malverde                           1
El Vallado                                 1
Industrial Penitenciaria                   1
Malecón                                    1
Bebelama de San Pedro                      1
Quilá                                      1
El Tule                                    1
Arca Continental                           1
Lo de Jesús                                1
Agua Blanca                                1
Bachigualatito                             1
Econo llantas                              1
Citicinemas La Isla                        1
Colotlán                                   1
Zóquite                                    1
Tetillas                                   1
Genaro Codina                              1
San Ramón                                  1
Santo Domingo - Estación Catorce           1
La Cruz Centro                             1
La Cruz - Celestino Gazca                  1
Entronque Villa Juárez                     1
El Castillo                                1
Concordia                                  1
Mazatlán - La Cruz                         1
La Cruz - Culiacán                         1
Pueblos Unidos                             1
Navolato Centro                            1
Playa Humaya                               1
Jardín Botánico                            1
Centro Guadalupe                           1
El Silencio                                1
Tránsito                                   1
SAT                                        1
Cerro Papanton                             1
Parque Culiacán 87                         1
El Sifón                                   1
Huizaches                                  1
Aguascalientes Centro                      1
Waltmart                                   1
Soriana Tres Cruces                        1
Fracc. Dependencias Federales              1
Muebles DICO                               1
Viñedos, Querétaro                         1
Calle 6, Querétaro                         1
Querétaro Centro                           1
Musalá                                     1
Colonia Michoacana                         1
El Triguito                                1
Playa Ceuta                                1
Celestino Gazca                            1
Parque Ribieras                            1
Parroquia La Sagrada Familia               1
Tasty Chicken                              1
Boulevard Emiliano Zapata                  1
Superblock                                 1
Parque Acuático Tres Ríos                  1
Entronque a El Quemadito                   1
Ley Del Valle                              1
Bachigualatillo                            1
Metro Pantitlán                            1
Tenayuca                                   1
Lomas de Sotelo                            1
Costa Azul                                 1
Isla El Maviri                             1
Topolobampo Malecón                        1
Guamúchil Centro                           1
Villas del Río                             1
Entronque a Villas del Río                 1
La Palma                                   1
Colonia Roma Norte                         1
Metro Tacuba                               1
Metro Cuitláhuac                           1
Cerro de la Estrella                       1
Nueve Parroquias, CDMX                     1
Agencia Hyundai                            1
Centro Comercial Diagonal                  1
CONIN                                      1
Hacienda Nueva                             1
El Barril                                  1
Conde de Santiago                          1
Soriana Gavilanes                          1
Durango Centro                             1
Culiacán - Guasave                         1
Parque México                              1
Metro Popotla                              1
Pánuco                                     1
Los Ayala                                  1
Rincón de Guayavitos                       1
Durango - Sombrerete                       1
Sombrerete - Fresnillo                     1
Nissan 2                                   1
Presa El Mastranto                         1
Buenavista - Roca Partida                  1
TAPO                                       1
Bariometo II                               1
Walmart CEDIS                              1
Casetas San Pedro - Costa Rica             1
Metrobús Hospital La Raza                  1
Ojo de Agua de la Palma                    1
AICM                                       1
IPN Zacatenco                              1
Lay del Valle                              1
Hotel NH San Pedro                         1
Cerca de Tolosa                            1
Rodeo Bernardez                            1
Ciénaga de Villareales                     1
San Pedro Ocotlán                          1
Rincón de Romos - Mexquitic                1
Mezquitic - Moctezuma                      1
Chaparrosa                                 1
Guadalupe - Calvillo                       1
Calvillo - Nochistlán                      1
Nochistlán - Tepatitlán                    1
Valle Alto                                 1
Name: count, dtype: int64

In [9]:
df1.loc[:,'Nombre de la actividad'] = dfact['Activity']
df1.tail()

,Id. de actividad,Fecha de la actividad,Nombre de la actividad,Tipo de actividad,Tiempo transcurrido,Distancia,Ritmo cardíaco máx.,Esfuerzo relativo,Viaje al trabajo,Equipamiento de la actividad,Nombre de archivo,Peso de la bicicleta,Tiempo transcurrido.1,Tiempo en movimiento,Distancia.1,Velocidad máxima,Velocidad promedio,Desnivel positivo,Desnivel negativo,Desnivel bajo,Desnivel alto,Grado máximo,Pendiente promedio,Ritmo cardíaco promedio,Vatios promedio,Calorías,Esfuerzo relativo.1,Usar Esfuerzo Percibido,Viaje al trabajo.1,De carga,Bicicleta,Marcado,Velocidad promedio durante el tiempo transcurrido,Distancia sobre tierra,Descripción de la actividad
2637,15220567000,2013-09-14 00:00:00,Durango - Mazatlán,Ciclismo,52883,256.22,NaN,NaN,False,Trek X-Caliber 9,activities/16254211104.gpx.gz,14.5,52883.0,37419.0,256221.093750,23.754728,6.847353,4101.606934,5634.478516,1.5,2741.699951,49.995838,-0.743616,NaN,120.193291,5014.714355,NaN,NaN,0.0,1.0,5230367.0,0.0,4.845056,15.400000,Tour Ruta Chichimeca
2638,15220633781,2017-07-26 00:00:00,Mazatlán - Potrerillos,Ciclismo,33601,103.21,142.0,97.0,False,Trek X-Caliber 9,activities/16254282832.gpx.gz,14.5,33601.0,24048.0,103217.960938,17.015110,4.292164,2071.595703,554.852356,1.2,1520.099976,24.497150,1.470093,112.553719,110.959236,2975.201416,97.0,NaN,0.0,1.0,5230367.0,NaN,3.071872,808.099976,Tour Ruta Chichimeca
2639,15220738336,2014-07-26 00:00:00,Mazatlán - Potrerillos,Ciclismo,37254,131.10,NaN,NaN,False,Trek X-Caliber 9,activities/16254394819.gpx.gz,14.5,37254.0,29261.0,131105.859375,15.921565,4.480567,1617.736084,493.804260,1.2,1522.900024,24.581144,1.158453,NaN,98.030838,3198.354248,NaN,NaN,0.0,1.0,5230367.0,NaN,3.519243,931.599976,Tour Ruta Chichimeca
2640,15227330540,2025-07-24 00:00:00,Ley del Valle,Caminata,3282,3.59,101.0,5.0,False,Adidas Terrex Eastrail,activities/16261402744.fit.gz,NaN,3282.0,2932.0,3596.199951,2.174000,1.097000,24.024540,167.000000,28.1,43.500000,20.270269,0.000000,79.000000,NaN,244.000000,5.0,NaN,0.0,1.0,NaN,NaN,1.095734,0.000000,Culiacán
2641,15227332434,2025-07-25 00:00:00,La Platanera,Ciclismo,8409,51.85,149.0,56.0,False,Trek X-Caliber 9,activities/16261404830.fit.gz,14.5,8409.0,8242.0,51856.101562,12.699000,6.168000,145.078339,200.000000,18.1,47.700001,7.416268,0.000771,121.000000,83.107635,1044.000000,56.0,NaN,0.0,1.0,5230367.0,NaN,6.166738,5363.000000,NaN

## Clean Activity Description

In [10]:
# Copy 'Id. de actividad' y 'Descripción de la actividad' en un dataframe nuevo
dfact = df1[df1['Tipo de actividad'] == 'Ciclismo'][['Id. de actividad', 'Nombre de la actividad', 'Descripción de la actividad']].copy()
print(f"Dataframe shape: {dfact.shape}")
print(f"Non-empty rows: {(~dfact['Descripción de la actividad'].isnull()).sum()}")
dfact.head()

Dataframe shape: (2030, 3)
Non-empty rows: 375

   Id. de actividad   Nombre de la actividad Descripción de la actividad
0         353375734                Zacatecas            Vuelta a la Bufa
1         353377512                 Tepetate                         NaN
2         353380425  Nochistlán - Tepatitlán               Tour Personal
3         353381733    Calvillo - Nochistlán               Tour Personal
4         353384459     Guadalupe - Calvillo               Tour Personal

In [11]:
# Identify the rows with 'Carrera' as the first word in 'Descripción de la actividad'. Define a
# new column 'Tipo rodada' and assign 'Carrera' to those rows.
dfact['Descripción de rodada'] = dfact['Descripción de la actividad'].str.split().str[0]
dfact['Tipo rodada'] = 'Vuelta'
dfact.loc[dfact['Nombre de la actividad'] == 'Tec de Monterrey', 'Tipo rodada'] = 'Commute'
dfact.loc[dfact['Descripción de rodada'] == 'Carrera', 'Tipo rodada'] = 'Carrera'
dfact.loc[dfact['Descripción de rodada'] == 'Tour', 'Tipo rodada'] = 'Tour'
dfact['Tipo rodada'].value_counts()

Tipo rodada
Commute    973
Vuelta     965
Tour        65
Carrera     27
Name: count, dtype: int64

In [12]:
# Merge dfact to df1 according to 'Id. de actividad'
df1 = df1.merge(dfact[['Id. de actividad', 'Tipo rodada']], on='Id. de actividad', how='left')
df1.head()

,Id. de actividad,Fecha de la actividad,Nombre de la actividad,Tipo de actividad,Tiempo transcurrido,Distancia,Ritmo cardíaco máx.,Esfuerzo relativo,Viaje al trabajo,Equipamiento de la actividad,Nombre de archivo,Peso de la bicicleta,Tiempo transcurrido.1,Tiempo en movimiento,Distancia.1,Velocidad máxima,Velocidad promedio,Desnivel positivo,Desnivel negativo,Desnivel bajo,Desnivel alto,Grado máximo,Pendiente promedio,Ritmo cardíaco promedio,Vatios promedio,Calorías,Esfuerzo relativo.1,Usar Esfuerzo Percibido,Viaje al trabajo.1,De carga,Bicicleta,Marcado,Velocidad promedio durante el tiempo transcurrido,Distancia sobre tierra,Descripción de la actividad,Tipo rodada
0,353375734,2015-07-24 00:00:00,Zacatecas,Ciclismo,3069,14.33,NaN,NaN,False,TREK 8500,activities/400134783.gpx.gz,16.0,3069.0,3069.0,14330.299805,18.1,NaN,406.476013,427.936951,2308.600098,2554.899902,26.900000,-0.048150,NaN,197.826767,676.950317,NaN,0.0,0.0,NaN,2169839.0,NaN,NaN,7331.000000,Vuelta a la Bufa,Vuelta
1,353377512,2015-07-19 00:00:00,Tepetate,Ciclismo,22770,92.15,NaN,NaN,False,TREK 8500,activities/400136595.gpx.gz,16.0,22770.0,16473.0,92158.398438,13.2,NaN,791.320007,874.078064,2219.699951,2473.500000,21.000000,-0.002279,NaN,166.551178,3059.111328,NaN,0.0,0.0,NaN,2169839.0,NaN,NaN,20137.599609,NaN,Vuelta
2,353380425,2015-07-13 00:00:00,Nochistlán - Tepatitlán,Ciclismo,30131,98.53,NaN,NaN,False,TREK 8500,activities/400139647.gpx.gz,16.0,30131.0,19435.0,98532.398438,15.2,NaN,1550.469971,1744.161743,1453.300049,2091.800049,40.400002,-0.117728,NaN,169.094589,3664.292969,NaN,0.0,0.0,NaN,2169839.0,NaN,NaN,785.599976,Tour Personal,Tour
3,353381733,2015-07-12 00:00:00,Calvillo - Nochistlán,Ciclismo,41874,114.20,NaN,NaN,False,TREK 8500,activities/400140985.gpx.gz,16.0,41874.0,28662.0,114199.000000,15.2,NaN,2102.399902,2093.768555,1640.000000,2417.800049,39.200001,0.209809,NaN,143.750061,4593.980957,NaN,0.0,0.0,NaN,2169839.0,NaN,NaN,21528.099609,Tour Personal,Tour
4,353384459,2015-07-11 00:00:00,Guadalupe - Calvillo,Ciclismo,43152,151.96,NaN,NaN,False,TREK 8500,activities/400143736.gpx.gz,16.0,43152.0,30451.0,151961.000000,18.4,NaN,1738.469971,2602.712891,1640.000000,2455.100098,27.500000,-0.457881,NaN,153.353729,5206.807617,NaN,0.0,0.0,NaN,2169839.0,NaN,NaN,50302.500000,Tour Personal,Tour

## Make numeric columns

In [13]:
# Numeric columns
cols = ['Tiempo transcurrido', 'Distancia', 'Ritmo cardíaco máx.', 'Esfuerzo relativo', 'Peso de la bicicleta',
        'Tiempo en movimiento', 'Velocidad máxima', 'Velocidad promedio', 'Desnivel positivo', 'Desnivel negativo', 
        'Desnivel bajo', 'Desnivel alto', 'Grado máximo', 'Pendiente promedio','Ritmo cardíaco promedio', 
        'Vatios promedio', 'Calorías', 'Marcado', 'Velocidad promedio durante el tiempo transcurrido',
       'Distancia sobre tierra']
df = df1.drop(columns=['Tiempo transcurrido.1', 'Distancia.1', 'Esfuerzo relativo.1', 'Usar Esfuerzo Percibido',
                       'Viaje al trabajo.1', 'De carga', 'Bicicleta'])
# Convert to numeric
df.loc[:, cols] = df[cols].apply(pd.to_numeric, errors='coerce')
df.head()

,Id. de actividad,Fecha de la actividad,Nombre de la actividad,Tipo de actividad,Tiempo transcurrido,Distancia,Ritmo cardíaco máx.,Esfuerzo relativo,Viaje al trabajo,Equipamiento de la actividad,Nombre de archivo,Peso de la bicicleta,Tiempo en movimiento,Velocidad máxima,Velocidad promedio,Desnivel positivo,Desnivel negativo,Desnivel bajo,Desnivel alto,Grado máximo,Pendiente promedio,Ritmo cardíaco promedio,Vatios promedio,Calorías,Marcado,Velocidad promedio durante el tiempo transcurrido,Distancia sobre tierra,Descripción de la actividad,Tipo rodada
0,353375734,2015-07-24 00:00:00,Zacatecas,Ciclismo,3069,14.33,NaN,NaN,False,TREK 8500,activities/400134783.gpx.gz,16.0,3069.0,18.1,NaN,406.476013,427.936951,2308.600098,2554.899902,26.900000,-0.048150,NaN,197.826767,676.950317,NaN,NaN,7331.000000,Vuelta a la Bufa,Vuelta
1,353377512,2015-07-19 00:00:00,Tepetate,Ciclismo,22770,92.15,NaN,NaN,False,TREK 8500,activities/400136595.gpx.gz,16.0,16473.0,13.2,NaN,791.320007,874.078064,2219.699951,2473.500000,21.000000,-0.002279,NaN,166.551178,3059.111328,NaN,NaN,20137.599609,NaN,Vuelta
2,353380425,2015-07-13 00:00:00,Nochistlán - Tepatitlán,Ciclismo,30131,98.53,NaN,NaN,False,TREK 8500,activities/400139647.gpx.gz,16.0,19435.0,15.2,NaN,1550.469971,1744.161743,1453.300049,2091.800049,40.400002,-0.117728,NaN,169.094589,3664.292969,NaN,NaN,785.599976,Tour Personal,Tour
3,353381733,2015-07-12 00:00:00,Calvillo - Nochistlán,Ciclismo,41874,114.20,NaN,NaN,False,TREK 8500,activities/400140985.gpx.gz,16.0,28662.0,15.2,NaN,2102.399902,2093.768555,1640.000000,2417.800049,39.200001,0.209809,NaN,143.750061,4593.980957,NaN,NaN,21528.099609,Tour Personal,Tour
4,353384459,2015-07-11 00:00:00,Guadalupe - Calvillo,Ciclismo,43152,151.96,NaN,NaN,False,TREK 8500,activities/400143736.gpx.gz,16.0,30451.0,18.4,NaN,1738.469971,2602.712891,1640.000000,2455.100098,27.500000,-0.457881,NaN,153.353729,5206.807617,NaN,NaN,50302.500000,Tour Personal,Tour

## Save results

In [14]:
# Save the cleaned data to a new excel file
df.to_excel('../data/strava_ips.xlsx', index=False)